defaults: &defaults
  host: '127.0.0.1'
  autocreate_indexes: false
  allow_dynamic_fields: true
  include_root_in_json: false
  parameterize_keys: true
  persist_in_safe_mode: false
  raise_not_found_error: true
  reconnect_time: 3

development:
  <<: *defaults
  database: kkdianping_development

development_mongohq:
  <<: *defaults
  #uri: mongodb://<user>:<password>@flame.mongohq.com:27070/kkdp
  #use demo mongohq database for fast run
  uri: mongodb://root:666666@flame.mongohq.com:27070/kkdp

test:
  <<: *defaults
  database: kkdianping_test

# set these environment variables on your prod server
production:
  <<: *defaults
  host: '127.0.0.1'
  database: kkdianping_development

